.TH "PYCHING" "1" "27 Feb 2006" "" ""
.SH "NAME"
pyching \- cast and interpret I Ching hexagrams
.SH "SYNOPSIS"
.B pyching
.BR \-h | \-\-help
.br 
.B pyching
.BR \-v | \-\-version
.br 
.B pyching
.RB [ \-d | \-\-disable\-version\-check ]
.SH "DESCRIPTION"
.B pyChing
is a Python program that allows you to consult the I Ching.  The I
Ching is an ancient Chinese book of wisdom, which, apart from being
read as a book, has also traditionally been consulted as an oracle.
.B pyChing
allows you to perform an I Ching reading using the coin method, and
then look up a brief interpretation from the I Ching.
.PP 
For further information, consult the online documentation available by
way of the program's
.B Help
menu.
.SH "OPTIONS"
.TP 
.B \-h, \-\-help
Display a summary of command\-line options.
.TP 
.B \-v, \-\-version
Display version information.
.TP 
.B \-d, \-\-disable\-version\-check
Suppress the initial check for appropriate versions of Python and Tk.
.SH "AUTHOR"
.B pyChing
was written by Stephen M. Gava <elguavas@users.sourceforge.net>.
This manual page is based on the one originally written by Colin Watson <cjwatson@debian.org> for
the Debian GNU system. Thanks Colin.
